Repository cloud-native-toolkit/terraform-provider-clis, pull requests merged in 2022-09, with the labels that each got.

#1 Implements logic to download clis into bin_dir
  .github/release-drafter.yaml
  .github/scripts/validate-deploy.sh
  .github/workflows/release.yml
  .github/workflows/verify-pr.yaml
  .github/workflows/verify.yaml
  .gitignore
  .goreleaser.yml
  Makefile
  README.md
  clis/data_clis_check.go
  clis/helpers.go
  clis/provider.go
  docs/data-sources/check.md
  docs/index.md
  examples/apply.sh
  examples/destroy.sh
  examples/gitops_module/main.tf
  examples/gitops_module/variables.tf
  examples/gitops_module/yaml/mymodule.yaml
  examples/gitops_namespace/main.tf
  examples/gitops_namespace/outputs.tf
  examples/gitops_namespace/variables.tf
  examples/gitops_namespace/yaml/ns.yaml
  examples/main.tf
  examples/provider.tf
  examples/reset.sh
  examples/stage1-cert.tf
  examples/stage1-clis.tf
  examples/stage1-gitops.tf
  examples/stage2-namespace.tf
  examples/stage3-mymodule.tf
  examples/terraform.tfvars
  examples/variables.tf
  examples/version.tf
  gitops/provider.go
  gitops/resource_gitops_module.go
  gitops/resource_gitops_namespace.go
  go.mod
  go.sum
  main.go
  terraform-registry-manifest.json
Labels: feature, minor

#2 Adds verifyReleaser to PR process
  .github/workflows/verify-pr.yaml
  clis/data_clis_check.go
  examples/stage1-clis.tf
Labels: chore, patch

#3 Adds openshift-install cli
  .github/scripts/validate-deploy.sh
  clis/data_clis_check.go
  examples/stage1-clis.tf
Labels: feature, minor

#4 Updates version to 0.2.0
  Makefile
Labels: chore, patch

#6 Updates version to 0.2.1
  Makefile
Labels: chore, patch

#7 Add detection and support for alpine clis
  clis/data_clis_check.go
  clis/helpers.go
  clis/provider.go
Labels: bug, patch

#8 Updates version to 0.2.2
  Makefile
Labels: chore, patch

#9 Updates validation test for clis from tgz files
  clis/data_clis_check.go
Labels: bug, patch

#10 Updates version to 0.2.3
  Makefile
Labels: chore, patch

#11 Fixes issue of missing version number from lookup
  clis/data_clis_check.go
Labels: bug, patch

#12 Updates version to 0.2.4
  Makefile
Labels: chore, patch
